package com.apkbus.weather.db.Dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.apkbus.weather.db.Bean.DistrictBean;
import com.apkbus.weather.db.DaoSession;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISTRICT_BEAN".
*/
public class DistrictBeanDao extends AbstractDao<DistrictBean, Long> {

    public static final String TABLENAME = "DISTRICT_BEAN";

    /**
     * Properties of entity DistrictBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property CityName = new Property(1, String.class, "cityName", false, "CITY_NAME");
        public final static Property DistrictName = new Property(2, String.class, "districtName", false, "DISTRICT_NAME");
        public final static Property Level = new Property(3, int.class, "level", false, "LEVEL");
    }


    public DistrictBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DistrictBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISTRICT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"CITY_NAME\" TEXT," + // 1: cityName
                "\"DISTRICT_NAME\" TEXT," + // 2: districtName
                "\"LEVEL\" INTEGER NOT NULL );"); // 3: level
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DISTRICT_BEAN_CITY_NAME ON \"DISTRICT_BEAN\"" +
                " (\"CITY_NAME\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_DISTRICT_BEAN_DISTRICT_NAME ON \"DISTRICT_BEAN\"" +
                " (\"DISTRICT_NAME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISTRICT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DistrictBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String cityName = entity.getCityName();
        if (cityName != null) {
            stmt.bindString(2, cityName);
        }
 
        String districtName = entity.getDistrictName();
        if (districtName != null) {
            stmt.bindString(3, districtName);
        }
        stmt.bindLong(4, entity.getLevel());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DistrictBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String cityName = entity.getCityName();
        if (cityName != null) {
            stmt.bindString(2, cityName);
        }
 
        String districtName = entity.getDistrictName();
        if (districtName != null) {
            stmt.bindString(3, districtName);
        }
        stmt.bindLong(4, entity.getLevel());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public DistrictBean readEntity(Cursor cursor, int offset) {
        DistrictBean entity = new DistrictBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cityName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // districtName
            cursor.getInt(offset + 3) // level
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DistrictBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setCityName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDistrictName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLevel(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DistrictBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DistrictBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DistrictBean entity) {
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
}
