package com.apkbus.weather.db

import org.greenrobot.greendao.AbstractDao
import org.greenrobot.greendao.AbstractDaoSession
import org.greenrobot.greendao.database.Database
import org.greenrobot.greendao.identityscope.IdentityScopeType
import org.greenrobot.greendao.internal.DaoConfig

import com.apkbus.weather.db.Bean.CityBean
import com.apkbus.weather.db.Bean.DistrictBean
import com.apkbus.weather.db.Bean.ProvinceBean
import com.apkbus.weather.db.Dao.CityBeanDao
import com.apkbus.weather.db.Dao.DistrictBeanDao
import com.apkbus.weather.db.Dao.ProvinceBeanDao

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
class DaoSession(db: Database, type: IdentityScopeType, daoConfigMap: Map<Class<out AbstractDao<*, *>>, DaoConfig>) : AbstractDaoSession(db) {
    private val cityBeanDaoConfig: DaoConfig = daoConfigMap[CityBeanDao::class.java]!!.clone()
    private val districtBeanDaoConfig: DaoConfig
    private val provinceBeanDaoConfig: DaoConfig

    val cityBeanDao: CityBeanDao
    val districtBeanDao: DistrictBeanDao
    val provinceBeanDao: ProvinceBeanDao

    init {
        cityBeanDaoConfig.initIdentityScope(type)

        districtBeanDaoConfig = daoConfigMap[DistrictBeanDao::class.java]!!.clone()
        districtBeanDaoConfig.initIdentityScope(type)

        provinceBeanDaoConfig = daoConfigMap[ProvinceBeanDao::class.java]!!.clone()
        provinceBeanDaoConfig.initIdentityScope(type)

        cityBeanDao = CityBeanDao(cityBeanDaoConfig, this)
        districtBeanDao = DistrictBeanDao(districtBeanDaoConfig, this)
        provinceBeanDao = ProvinceBeanDao(provinceBeanDaoConfig, this)

        registerDao(CityBean::class.java, cityBeanDao)
        registerDao(DistrictBean::class.java, districtBeanDao)
        registerDao(ProvinceBean::class.java, provinceBeanDao)
    }

    fun clear() {
        cityBeanDaoConfig.clearIdentityScope()
        districtBeanDaoConfig.clearIdentityScope()
        provinceBeanDaoConfig.clearIdentityScope()
    }
}
