package com.apkbus.weather.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.apkbus.weather.db.CityBean;
import com.apkbus.weather.db.DistrictBean;
import com.apkbus.weather.db.ProvinceBean;

import com.apkbus.weather.db.CityBeanDao;
import com.apkbus.weather.db.DistrictBeanDao;
import com.apkbus.weather.db.ProvinceBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityBeanDaoConfig;
    private final DaoConfig districtBeanDaoConfig;
    private final DaoConfig provinceBeanDaoConfig;

    private final CityBeanDao cityBeanDao;
    private final DistrictBeanDao districtBeanDao;
    private final ProvinceBeanDao provinceBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityBeanDaoConfig = daoConfigMap.get(CityBeanDao.class).clone();
        cityBeanDaoConfig.initIdentityScope(type);

        districtBeanDaoConfig = daoConfigMap.get(DistrictBeanDao.class).clone();
        districtBeanDaoConfig.initIdentityScope(type);

        provinceBeanDaoConfig = daoConfigMap.get(ProvinceBeanDao.class).clone();
        provinceBeanDaoConfig.initIdentityScope(type);

        cityBeanDao = new CityBeanDao(cityBeanDaoConfig, this);
        districtBeanDao = new DistrictBeanDao(districtBeanDaoConfig, this);
        provinceBeanDao = new ProvinceBeanDao(provinceBeanDaoConfig, this);

        registerDao(CityBean.class, cityBeanDao);
        registerDao(DistrictBean.class, districtBeanDao);
        registerDao(ProvinceBean.class, provinceBeanDao);
    }
    
    public void clear() {
        cityBeanDaoConfig.clearIdentityScope();
        districtBeanDaoConfig.clearIdentityScope();
        provinceBeanDaoConfig.clearIdentityScope();
    }

    public CityBeanDao getCityBeanDao() {
        return cityBeanDao;
    }

    public DistrictBeanDao getDistrictBeanDao() {
        return districtBeanDao;
    }

    public ProvinceBeanDao getProvinceBeanDao() {
        return provinceBeanDao;
    }

}
