package com.apkbus.weather.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROVINCE_BEAN".
*/
public class ProvinceBeanDao extends AbstractDao<ProvinceBean, Long> {

    public static final String TABLENAME = "PROVINCE_BEAN";

    /**
     * Properties of entity ProvinceBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ProvinceName = new Property(1, String.class, "provinceName", false, "PROVINCE_NAME");
        public final static Property Level = new Property(2, int.class, "level", false, "LEVEL");
    }


    public ProvinceBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ProvinceBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROVINCE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"PROVINCE_NAME\" TEXT," + // 1: provinceName
                "\"LEVEL\" INTEGER NOT NULL );"); // 2: level
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_PROVINCE_BEAN_PROVINCE_NAME ON \"PROVINCE_BEAN\"" +
                " (\"PROVINCE_NAME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROVINCE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProvinceBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String provinceName = entity.getProvinceName();
        if (provinceName != null) {
            stmt.bindString(2, provinceName);
        }
        stmt.bindLong(3, entity.getLevel());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProvinceBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String provinceName = entity.getProvinceName();
        if (provinceName != null) {
            stmt.bindString(2, provinceName);
        }
        stmt.bindLong(3, entity.getLevel());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ProvinceBean readEntity(Cursor cursor, int offset) {
        ProvinceBean entity = new ProvinceBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // provinceName
            cursor.getInt(offset + 2) // level
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProvinceBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setProvinceName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLevel(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProvinceBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProvinceBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProvinceBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
